import 'dart:convert';
import 'dart:io';

import 'package:analisis_riesgo_app/services/api_service.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';

void main() {
  group('ApiService', () {
    test('parses a successful response payload', () async {
      final mock = MockClient((request) async {
        expect(request.url.path, '/analyse');
        expect(request.method, 'POST');
        final body = jsonDecode(request.body) as Map<String, dynamic>;
        expect(body['returns'], isA<List<dynamic>>());
        expect(body['investment_amount'], 1000000);
        expect(body['var_confidence'], 0.95);
        expect(body['target_accept'], 0.9);

        return http.Response(
          jsonEncode({
            'var_value': 50000.0,
            'threshold_probability': 0.05,
            'investment_amount': 1000000.0,
            'var_confidence': 0.95,
            'loss_threshold': 50000.0,
            'parameter_means': {
              'media_retorno': -0.001,
              'desviacion_retorno': 0.02,
            },
            'histogram_base64': 'abc123',
          }),
          200,
          headers: {'content-type': 'application/json'},
        );
      });

      final service = ApiService(baseUrl: 'http://x', client: mock);
      final result = await service.analyse(returns: [-0.1, 0.1]);

      expect(result.varValue, 50000.0);
      expect(result.thresholdProbability, 0.05);
      expect(result.parameterMeans['media_retorno'], -0.001);
      expect(result.histogramBase64, 'abc123');
    });

    test('throws on error status with backend detail', () async {
      final mock = MockClient((request) async {
        return http.Response(
          jsonEncode({'detail': 'Datos de entrada invalidos'}),
          400,
          headers: {'content-type': 'application/json'},
        );
      });

      final service = ApiService(baseUrl: 'http://x', client: mock);
      await expectLater(
        service.analyse(returns: [-0.1, 0.1]),
        throwsA(
          isA<Exception>().having(
            (e) => e.toString(),
            'message',
            contains('Datos de entrada invalidos'),
          ),
        ),
      );
    });

    test('throws on non-json error body', () async {
      final mock = MockClient((request) async {
        return http.Response('upstream exploded', 500);
      });

      final service = ApiService(baseUrl: 'http://x', client: mock);
      await expectLater(
        service.analyse(returns: [-0.1, 0.1]),
        throwsA(isA<Exception>()),
      );
    });

    test('decodes the response example generated by the backend', () {
      // Written by `python -m backend.test_contract` from RiskResponse, and kept
      // fresh by backend/test_contract.py. Decoding it here is what fails when a
      // field is renamed on the Python side without updating this client.
      final contract =
          File('../backend/contract/risk_response.example.json');
      final payload =
          jsonDecode(contract.readAsStringSync()) as Map<String, dynamic>;

      final response = RiskResponse.fromJson(payload);

      expect(response.varValue, 50000.0);
      expect(response.thresholdProbability, 0.05);
      expect(response.parameterMeans, {
        'media_retorno': -0.001,
        'desviacion_retorno': 0.02,
        'nu': 8.0,
      });
    });

    // Payload captured from a real FastAPI 422 response body.
    test('renders 422 validation details as readable lines', () async {
      final mock = MockClient((request) async {
        return http.Response(
          jsonEncode({
            'detail': [
              {
                'type': 'less_than_equal',
                'loc': ['body', 'draws'],
                'msg': 'Input should be less than or equal to 10000',
                'input': 99999,
                'ctx': {'le': 10000},
              },
              {
                'type': 'greater_than_equal',
                'loc': ['body', 'tune'],
                'msg': 'Input should be greater than or equal to 200',
                'input': 10,
                'ctx': {'ge': 200},
              },
            ],
          }),
          422,
          headers: {'content-type': 'application/json'},
        );
      });

      final service = ApiService(baseUrl: 'http://x', client: mock);
      await expectLater(
        service.analyse(returns: [-0.1, 0.1]),
        throwsA(
          isA<Exception>().having(
            (e) => e.toString(),
            'message',
            allOf(
              contains('draws: Input should be less than or equal to 10000'),
              contains('tune: Input should be greater than or equal to 200'),
              isNot(contains('"loc"')),
            ),
          ),
        ),
      );
    });
  });
}